
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-demov2
  namespace: default  # Replace with your namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          env:
            # - name: my-secret-demo
            #   valueFrom:
            #     secretKeyRef:
            #       key: my-secret-demo
            #       name: my-secret-demo
            - name: my-cert-demo6
              valueFrom:
                secretKeyRef:
                  key: tls.crt
                  name: my-cert-demo6
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-sync