apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "f9537310-82f8-49b5-b9fe-c351b87501ac"
  name: "workload-identity-sa"
  namespace: "default"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "f9537310-82f8-49b5-b9fe-c351b87501ac"
    keyvaultName: keyvault-workload-idf850
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b" 
    objects:  |
      array:
        - |
          objectName: my-secretf8502a
          objectType: secret
          secretName: my-secretf8502a
  secretObjects:
    - secretName: my-secretf8502a
      type: Opaque
      data:
        - objectName: my-secretf8502a
          key: hello         

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default  # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
            - name: my_secret
              valueFrom:
                secretKeyRef:
                  name: my-secretf8502a
                  key: hello
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-wi"
