
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default  # Replace with your namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: weatherapi
          image: wklidentitypobfnoq76c5rcacr.azurecr.io/weatherapi:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          env:
            - name: mysql-secret
              valueFrom:
                secretKeyRef:
                  key: mysql-secret
                  name: mysql-secret
            - name: tls-crt
              valueFrom:
                secretKeyRef:
                  key: tls.crt
                  name: tls-crt
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-sync