apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "3dc95d44-0f2a-4999-af1f-66624c3b5bd5"
    keyvaultName: keyvault-workload-id8051
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b" 
    objects:  |
      array:
        - |
          objectName: "my-secret-demo"
          objectType: secret