apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6cdd01e0-43c4-4903-aac8-b9016cce779a"
    keyvaultName: "wkl-vahxlnengs6bg-kv"
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b"
    objects: |
      array:
        - |
          objectName: "my-secret-demo"
          objectType: secret
          secretName: "my-secret-demo"
        - |
          objectName: "workload-identity-cert"
          objectType: secret
          secretName: "workload-identity-cert"
  secretObjects:
    - secretName: my-secret-demo
      type: Opaque
      data:
        - key: my-secret-demo
          objectName: my-secret-demo
    - secretName: workload-identity-cert
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: workload-identity-cert
        - key: tls.key
          objectName: workload-identity-cert