apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "0ca4df74-d6f7-4c13-8a1a-e63cce515e75"
    keyvaultName: keyvault-workload-idf58e
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b"
    objects: |
      array:
        # - |
        #   objectName: "my-secret-demo"
        #   objectType: secret
        #   secretName: "my-secret-demo"
        - |
          objectName: "my-cert-demo6"
          objectType: cert
          secretName: "my-cert-demo6"
  secretObjects:
    # - secretName: my-secret-demo
    #   type: Opaque
    #   data:
    #     - key: my-secret-demo
    #       objectName: my-secret-demo
    - secretName: my-cert-demo6
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: my-cert-demo6
        - key: tls.key
          objectName: my-cert-demo6