apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6f678028-c19a-4c37-af0d-6fe9cb7a413e"
    keyvaultName: keyvault-workload-id317d
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b"
    objects: |
      array:
        - |
          objectName: "my-secret-demo"
          objectType: secret
          secretName: "my-secret-demo"
        - |
          objectName: "my-cert-demo"
          objectType: secret
          secretName: "my-cert-demo"
  secretObjects:
    - secretName: my-secret-demo
      type: Opaque
      data:
        - key: my-secret-demo
          objectName: my-secret-demo
    - secretName: my-cert-demo
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: my-cert-demo
        - key: tls.key
          objectName: my-cert-demo