apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "0d1ddd9c-e5c1-46af-8411-13c6b76c88d3"
    keyvaultName: keyvault-workload-id5ba6
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b"
    objects: |
      array:
        - |
          objectName: "my-secret-demo"
          objectType: secret
          secretName: "my-secret-demo"
  secretObjects:
    - secretName: my-secret-demo
      type: Opaque
      data:
        - key: my-secret-demo
          objectName: my-secret-demo
