apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "40e28bee-baaf-43dc-8ae7-09c013d6f14f"
    keyvaultName: "wkl-lvukgng7znr6s-kv"
    tenantId: "0e2ff29e-431a-420b-8a46-c6f39106927b"
    objects: |
      array:
        - |
          objectName: "mysql-secret"
          objectType: secret
          secretName: "mysql-secret"
        - |
          objectName: "tls-crt"
          objectType: secret
          secretName: "tls-crt"
  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - key: mysql-secret
          objectName: mysql-secret
    - secretName: tls-crt
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: tls-crt
        - key: tls.key
          objectName: tls-crt