apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-sync
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.SecretProviderClass.clientID }}
    keyvaultName: {{ .Values.SecretProviderClass.keyvaultName }}
    tenantId: {{ .Values.SecretProviderClass.tenantId }}
    objects: |
      array:
        - |
          objectName: "my-secret-demo"
          objectType: secret
          secretName: "my-secret-demo"
        - |
          objectName: "workload-identity-cert"
          objectType: secret
          secretName: "workload-identity-cert"
  secretObjects:
    - secretName: my-secret-demo
      type: Opaque
      data:
        - key: my-secret-demo
          objectName: my-secret-demo
    - secretName: workload-identity-cert
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: workload-identity-cert
        - key: tls.key
          objectName: workload-identity-cert