{{- /*
SecretProviderClass for Azure Key Vault integration using workload identity.
This template creates a SecretProviderClass that enables pods to access secrets
from Azure Key Vault using Azure Workload Identity.
*/}}

{{- $keyvaultName := required "A valid keyvault name is required" .Values.managedIdentity.keyvaultName }}
{{- $clientID := required "A valid managed identity client ID is required" .Values.managedIdentity.clientID }}
{{- $tenantId := required "A valid tenant ID is required" .Values.managedIdentity.tenantId }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.managedIdentity.secretProviderClassName | default "azure-kvname-wi" }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ $keyvaultName | quote }}
    clientID: {{ $clientID | quote }}
    tenantId: {{ $tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.managedIdentity.secretName }}
          secretName: {{ .Values.managedIdentity.secretName }}
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.managedIdentity.secretName }}
      type: Opaque
      data:
        - objectName: {{ .Values.managedIdentity.secretName }}
          key: {{ .Values.managedIdentity.secretKey | default "hello" }}