apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
  namespace: default  # Replace with your namespace
spec:
  type: LoadBalancer
  selector:
    app: weatherapi
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 81
    targetPort: 8081
    name: https
